[workspace]
resolver = "2"
members = [
    "contracts/*",
    "forwarder_executor"
]

[workspace.dependencies]
cosmwasm-schema = "2.2.0"
cosmwasm-std = { version = "2.2.1", features = [
    "cosmwasm_1_4",
    # Enable this if you only deploy to chains that have CosmWasm 2.0 or higher
    "cosmwasm_2_0",
    # Or this if you only deploy to chains that have CosmWasm 2.1 or higher
    # "cosmwasm_2_1",
] }
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
cw-ownable = { version = "2.1.0" }
cw-utils = { version = "2.0.0", default-features = false }
schemars = "0.8.16"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
thiserror = { version = "2.0.12" }
neutron-std = { version = "9.0.0" }
semver = { version = "1.0.22", default-features = false }
maxbtc-base = { path = "./packages/base" }
maxbtc-helpers = { path = "./packages/helpers" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
