[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --bin maxbtc-neutron-exchange-rate-provider-mock-schema"
integration-test = "test --lib integration_tests"
